pipeline {
  agent any

  stages {
    stage('Pull Latest Code') {
      steps {
        git credentialsId: 'github-ssh', url: 'git@github.com:naaakul/docker-deploy.git'
      }
    }

    stage('Deploy Locally via Ansible') {
      steps {
        bat '''
        wsl bash -c "cd /mnt/c/ProgramData/Jenkins/.jenkins/workspace/deploy-docker && ansible-playbook ansible/deploy-local.yml"
        '''
      }
    }
  }
}
