pipeline {
  agent none

  stages {
    stage('Build & Deploy on VM') {
      agent { label 'vm' }

      environment {
        APP_DIR = "/var/www/docker-deploy"
        REPO = "git@github.com:naaakul/docker-deploy.git"
        IMAGE = "docker-deploy-image"
        CONTAINER = "docker-deploy-container"
        PORT = "3000"
      }

      stages {

        stage('Install Dependencies') {
          steps {
            sh 'sudo apt update && sudo apt install -y docker.io nginx git'
          }
        }

        stage('Clone or Update Repo') {
          steps {
            sh '''
            mkdir -p $APP_DIR
            if [ ! -d "$APP_DIR/.git" ]; then
              git clone $REPO $APP_DIR
            else
              cd $APP_DIR && git pull
            fi
            '''
          }
        }

        stage('Build Docker Image') {
          steps {
            sh 'cd $APP_DIR/app && docker build -t $IMAGE .'
          }
        }

        stage('Restart Container') {
          steps {
            sh 'docker stop $CONTAINER || true'
            sh 'docker rm $CONTAINER || true'
            sh 'docker run -d -p $PORT:3000 --name $CONTAINER --restart always $IMAGE'
          }
        }

        stage('Configure Nginx') {
          steps {
            sh '''
            echo "server {
              listen 80;
              server_name _;
              location / {
                proxy_pass http://localhost:$PORT;
                proxy_http_version 1.1;
                proxy_set_header Upgrade \\$http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host \\$host;
                proxy_cache_bypass \\$http_upgrade;
              }
            }" | sudo tee /etc/nginx/sites-available/docker-deploy

            sudo ln -sf /etc/nginx/sites-available/docker-deploy /etc/nginx/sites-enabled/docker-deploy
            sudo systemctl reload nginx
            '''
          }
        }

      }
    }
  }
}
